###################################################################

# Created by write_sdc on Mon Jun 24 15:42:58 2024

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_max_area 0
set_load -pin_load 0 [get_ports {add1[31]}]
set_load -pin_load 0 [get_ports {add1[30]}]
set_load -pin_load 0 [get_ports {add1[29]}]
set_load -pin_load 0 [get_ports {add1[28]}]
set_load -pin_load 0 [get_ports {add1[27]}]
set_load -pin_load 0 [get_ports {add1[26]}]
set_load -pin_load 0 [get_ports {add1[25]}]
set_load -pin_load 0 [get_ports {add1[24]}]
set_load -pin_load 0 [get_ports {add1[23]}]
set_load -pin_load 0 [get_ports {add1[22]}]
set_load -pin_load 0 [get_ports {add1[21]}]
set_load -pin_load 0 [get_ports {add1[20]}]
set_load -pin_load 0 [get_ports {add1[19]}]
set_load -pin_load 0 [get_ports {add1[18]}]
set_load -pin_load 0 [get_ports {add1[17]}]
set_load -pin_load 0 [get_ports {add1[16]}]
set_load -pin_load 0 [get_ports {add1[15]}]
set_load -pin_load 0 [get_ports {add1[14]}]
set_load -pin_load 0 [get_ports {add1[13]}]
set_load -pin_load 0 [get_ports {add1[12]}]
set_load -pin_load 0 [get_ports {add1[11]}]
set_load -pin_load 0 [get_ports {add1[10]}]
set_load -pin_load 0 [get_ports {add1[9]}]
set_load -pin_load 0 [get_ports {add1[8]}]
set_load -pin_load 0 [get_ports {add1[7]}]
set_load -pin_load 0 [get_ports {add1[6]}]
set_load -pin_load 0 [get_ports {add1[5]}]
set_load -pin_load 0 [get_ports {add1[4]}]
set_load -pin_load 0 [get_ports {add1[3]}]
set_load -pin_load 0 [get_ports {add1[2]}]
set_load -pin_load 0 [get_ports {add1[1]}]
set_load -pin_load 0 [get_ports {add1[0]}]
set_load -pin_load 0 [get_ports {wen1[3]}]
set_load -pin_load 0 [get_ports {wen1[2]}]
set_load -pin_load 0 [get_ports {wen1[1]}]
set_load -pin_load 0 [get_ports {wen1[0]}]
set_load -pin_load 0 [get_ports {wdata1[31]}]
set_load -pin_load 0 [get_ports {wdata1[30]}]
set_load -pin_load 0 [get_ports {wdata1[29]}]
set_load -pin_load 0 [get_ports {wdata1[28]}]
set_load -pin_load 0 [get_ports {wdata1[27]}]
set_load -pin_load 0 [get_ports {wdata1[26]}]
set_load -pin_load 0 [get_ports {wdata1[25]}]
set_load -pin_load 0 [get_ports {wdata1[24]}]
set_load -pin_load 0 [get_ports {wdata1[23]}]
set_load -pin_load 0 [get_ports {wdata1[22]}]
set_load -pin_load 0 [get_ports {wdata1[21]}]
set_load -pin_load 0 [get_ports {wdata1[20]}]
set_load -pin_load 0 [get_ports {wdata1[19]}]
set_load -pin_load 0 [get_ports {wdata1[18]}]
set_load -pin_load 0 [get_ports {wdata1[17]}]
set_load -pin_load 0 [get_ports {wdata1[16]}]
set_load -pin_load 0 [get_ports {wdata1[15]}]
set_load -pin_load 0 [get_ports {wdata1[14]}]
set_load -pin_load 0 [get_ports {wdata1[13]}]
set_load -pin_load 0 [get_ports {wdata1[12]}]
set_load -pin_load 0 [get_ports {wdata1[11]}]
set_load -pin_load 0 [get_ports {wdata1[10]}]
set_load -pin_load 0 [get_ports {wdata1[9]}]
set_load -pin_load 0 [get_ports {wdata1[8]}]
set_load -pin_load 0 [get_ports {wdata1[7]}]
set_load -pin_load 0 [get_ports {wdata1[6]}]
set_load -pin_load 0 [get_ports {wdata1[5]}]
set_load -pin_load 0 [get_ports {wdata1[4]}]
set_load -pin_load 0 [get_ports {wdata1[3]}]
set_load -pin_load 0 [get_ports {wdata1[2]}]
set_load -pin_load 0 [get_ports {wdata1[1]}]
set_load -pin_load 0 [get_ports {wdata1[0]}]
set_load -pin_load 0 [get_ports {add2[31]}]
set_load -pin_load 0 [get_ports {add2[30]}]
set_load -pin_load 0 [get_ports {add2[29]}]
set_load -pin_load 0 [get_ports {add2[28]}]
set_load -pin_load 0 [get_ports {add2[27]}]
set_load -pin_load 0 [get_ports {add2[26]}]
set_load -pin_load 0 [get_ports {add2[25]}]
set_load -pin_load 0 [get_ports {add2[24]}]
set_load -pin_load 0 [get_ports {add2[23]}]
set_load -pin_load 0 [get_ports {add2[22]}]
set_load -pin_load 0 [get_ports {add2[21]}]
set_load -pin_load 0 [get_ports {add2[20]}]
set_load -pin_load 0 [get_ports {add2[19]}]
set_load -pin_load 0 [get_ports {add2[18]}]
set_load -pin_load 0 [get_ports {add2[17]}]
set_load -pin_load 0 [get_ports {add2[16]}]
set_load -pin_load 0 [get_ports {add2[15]}]
set_load -pin_load 0 [get_ports {add2[14]}]
set_load -pin_load 0 [get_ports {add2[13]}]
set_load -pin_load 0 [get_ports {add2[12]}]
set_load -pin_load 0 [get_ports {add2[11]}]
set_load -pin_load 0 [get_ports {add2[10]}]
set_load -pin_load 0 [get_ports {add2[9]}]
set_load -pin_load 0 [get_ports {add2[8]}]
set_load -pin_load 0 [get_ports {add2[7]}]
set_load -pin_load 0 [get_ports {add2[6]}]
set_load -pin_load 0 [get_ports {add2[5]}]
set_load -pin_load 0 [get_ports {add2[4]}]
set_load -pin_load 0 [get_ports {add2[3]}]
set_load -pin_load 0 [get_ports {add2[2]}]
set_load -pin_load 0 [get_ports {add2[1]}]
set_load -pin_load 0 [get_ports {add2[0]}]
set_load -pin_load 0 [get_ports {wen2[3]}]
set_load -pin_load 0 [get_ports {wen2[2]}]
set_load -pin_load 0 [get_ports {wen2[1]}]
set_load -pin_load 0 [get_ports {wen2[0]}]
set_load -pin_load 0 [get_ports {wdata2[31]}]
set_load -pin_load 0 [get_ports {wdata2[30]}]
set_load -pin_load 0 [get_ports {wdata2[29]}]
set_load -pin_load 0 [get_ports {wdata2[28]}]
set_load -pin_load 0 [get_ports {wdata2[27]}]
set_load -pin_load 0 [get_ports {wdata2[26]}]
set_load -pin_load 0 [get_ports {wdata2[25]}]
set_load -pin_load 0 [get_ports {wdata2[24]}]
set_load -pin_load 0 [get_ports {wdata2[23]}]
set_load -pin_load 0 [get_ports {wdata2[22]}]
set_load -pin_load 0 [get_ports {wdata2[21]}]
set_load -pin_load 0 [get_ports {wdata2[20]}]
set_load -pin_load 0 [get_ports {wdata2[19]}]
set_load -pin_load 0 [get_ports {wdata2[18]}]
set_load -pin_load 0 [get_ports {wdata2[17]}]
set_load -pin_load 0 [get_ports {wdata2[16]}]
set_load -pin_load 0 [get_ports {wdata2[15]}]
set_load -pin_load 0 [get_ports {wdata2[14]}]
set_load -pin_load 0 [get_ports {wdata2[13]}]
set_load -pin_load 0 [get_ports {wdata2[12]}]
set_load -pin_load 0 [get_ports {wdata2[11]}]
set_load -pin_load 0 [get_ports {wdata2[10]}]
set_load -pin_load 0 [get_ports {wdata2[9]}]
set_load -pin_load 0 [get_ports {wdata2[8]}]
set_load -pin_load 0 [get_ports {wdata2[7]}]
set_load -pin_load 0 [get_ports {wdata2[6]}]
set_load -pin_load 0 [get_ports {wdata2[5]}]
set_load -pin_load 0 [get_ports {wdata2[4]}]
set_load -pin_load 0 [get_ports {wdata2[3]}]
set_load -pin_load 0 [get_ports {wdata2[2]}]
set_load -pin_load 0 [get_ports {wdata2[1]}]
set_load -pin_load 0 [get_ports {wdata2[0]}]
set_load -pin_load 0 [get_ports {dbp_add1[9]}]
set_load -pin_load 0 [get_ports {dbp_add1[8]}]
set_load -pin_load 0 [get_ports {dbp_add1[7]}]
set_load -pin_load 0 [get_ports {dbp_add1[6]}]
set_load -pin_load 0 [get_ports {dbp_add1[5]}]
set_load -pin_load 0 [get_ports {dbp_add1[4]}]
set_load -pin_load 0 [get_ports {dbp_add1[3]}]
set_load -pin_load 0 [get_ports {dbp_add1[2]}]
set_load -pin_load 0 [get_ports {dbp_add1[1]}]
set_load -pin_load 0 [get_ports {dbp_add1[0]}]
set_load -pin_load 0 [get_ports {dbp_add2[9]}]
set_load -pin_load 0 [get_ports {dbp_add2[8]}]
set_load -pin_load 0 [get_ports {dbp_add2[7]}]
set_load -pin_load 0 [get_ports {dbp_add2[6]}]
set_load -pin_load 0 [get_ports {dbp_add2[5]}]
set_load -pin_load 0 [get_ports {dbp_add2[4]}]
set_load -pin_load 0 [get_ports {dbp_add2[3]}]
set_load -pin_load 0 [get_ports {dbp_add2[2]}]
set_load -pin_load 0 [get_ports {dbp_add2[1]}]
set_load -pin_load 0 [get_ports {dbp_add2[0]}]
set_load -pin_load 0 [get_ports dbp_wen2]
set_load -pin_load 0 [get_ports {dbp_wdata2[33]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[32]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[31]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[30]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[29]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[28]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[27]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[26]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[25]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[24]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[23]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[22]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[21]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[20]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[19]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[18]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[17]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[16]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[15]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[14]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[13]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[12]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[11]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[10]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[9]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[8]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[7]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[6]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[5]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[4]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[3]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[2]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[1]}]
set_load -pin_load 0 [get_ports {dbp_wdata2[0]}]
set_load -pin_load 0 [get_ports {cipher[127]}]
set_load -pin_load 0 [get_ports {cipher[126]}]
set_load -pin_load 0 [get_ports {cipher[125]}]
set_load -pin_load 0 [get_ports {cipher[124]}]
set_load -pin_load 0 [get_ports {cipher[123]}]
set_load -pin_load 0 [get_ports {cipher[122]}]
set_load -pin_load 0 [get_ports {cipher[121]}]
set_load -pin_load 0 [get_ports {cipher[120]}]
set_load -pin_load 0 [get_ports {cipher[119]}]
set_load -pin_load 0 [get_ports {cipher[118]}]
set_load -pin_load 0 [get_ports {cipher[117]}]
set_load -pin_load 0 [get_ports {cipher[116]}]
set_load -pin_load 0 [get_ports {cipher[115]}]
set_load -pin_load 0 [get_ports {cipher[114]}]
set_load -pin_load 0 [get_ports {cipher[113]}]
set_load -pin_load 0 [get_ports {cipher[112]}]
set_load -pin_load 0 [get_ports {cipher[111]}]
set_load -pin_load 0 [get_ports {cipher[110]}]
set_load -pin_load 0 [get_ports {cipher[109]}]
set_load -pin_load 0 [get_ports {cipher[108]}]
set_load -pin_load 0 [get_ports {cipher[107]}]
set_load -pin_load 0 [get_ports {cipher[106]}]
set_load -pin_load 0 [get_ports {cipher[105]}]
set_load -pin_load 0 [get_ports {cipher[104]}]
set_load -pin_load 0 [get_ports {cipher[103]}]
set_load -pin_load 0 [get_ports {cipher[102]}]
set_load -pin_load 0 [get_ports {cipher[101]}]
set_load -pin_load 0 [get_ports {cipher[100]}]
set_load -pin_load 0 [get_ports {cipher[99]}]
set_load -pin_load 0 [get_ports {cipher[98]}]
set_load -pin_load 0 [get_ports {cipher[97]}]
set_load -pin_load 0 [get_ports {cipher[96]}]
set_load -pin_load 0 [get_ports {cipher[95]}]
set_load -pin_load 0 [get_ports {cipher[94]}]
set_load -pin_load 0 [get_ports {cipher[93]}]
set_load -pin_load 0 [get_ports {cipher[92]}]
set_load -pin_load 0 [get_ports {cipher[91]}]
set_load -pin_load 0 [get_ports {cipher[90]}]
set_load -pin_load 0 [get_ports {cipher[89]}]
set_load -pin_load 0 [get_ports {cipher[88]}]
set_load -pin_load 0 [get_ports {cipher[87]}]
set_load -pin_load 0 [get_ports {cipher[86]}]
set_load -pin_load 0 [get_ports {cipher[85]}]
set_load -pin_load 0 [get_ports {cipher[84]}]
set_load -pin_load 0 [get_ports {cipher[83]}]
set_load -pin_load 0 [get_ports {cipher[82]}]
set_load -pin_load 0 [get_ports {cipher[81]}]
set_load -pin_load 0 [get_ports {cipher[80]}]
set_load -pin_load 0 [get_ports {cipher[79]}]
set_load -pin_load 0 [get_ports {cipher[78]}]
set_load -pin_load 0 [get_ports {cipher[77]}]
set_load -pin_load 0 [get_ports {cipher[76]}]
set_load -pin_load 0 [get_ports {cipher[75]}]
set_load -pin_load 0 [get_ports {cipher[74]}]
set_load -pin_load 0 [get_ports {cipher[73]}]
set_load -pin_load 0 [get_ports {cipher[72]}]
set_load -pin_load 0 [get_ports {cipher[71]}]
set_load -pin_load 0 [get_ports {cipher[70]}]
set_load -pin_load 0 [get_ports {cipher[69]}]
set_load -pin_load 0 [get_ports {cipher[68]}]
set_load -pin_load 0 [get_ports {cipher[67]}]
set_load -pin_load 0 [get_ports {cipher[66]}]
set_load -pin_load 0 [get_ports {cipher[65]}]
set_load -pin_load 0 [get_ports {cipher[64]}]
set_load -pin_load 0 [get_ports {cipher[63]}]
set_load -pin_load 0 [get_ports {cipher[62]}]
set_load -pin_load 0 [get_ports {cipher[61]}]
set_load -pin_load 0 [get_ports {cipher[60]}]
set_load -pin_load 0 [get_ports {cipher[59]}]
set_load -pin_load 0 [get_ports {cipher[58]}]
set_load -pin_load 0 [get_ports {cipher[57]}]
set_load -pin_load 0 [get_ports {cipher[56]}]
set_load -pin_load 0 [get_ports {cipher[55]}]
set_load -pin_load 0 [get_ports {cipher[54]}]
set_load -pin_load 0 [get_ports {cipher[53]}]
set_load -pin_load 0 [get_ports {cipher[52]}]
set_load -pin_load 0 [get_ports {cipher[51]}]
set_load -pin_load 0 [get_ports {cipher[50]}]
set_load -pin_load 0 [get_ports {cipher[49]}]
set_load -pin_load 0 [get_ports {cipher[48]}]
set_load -pin_load 0 [get_ports {cipher[47]}]
set_load -pin_load 0 [get_ports {cipher[46]}]
set_load -pin_load 0 [get_ports {cipher[45]}]
set_load -pin_load 0 [get_ports {cipher[44]}]
set_load -pin_load 0 [get_ports {cipher[43]}]
set_load -pin_load 0 [get_ports {cipher[42]}]
set_load -pin_load 0 [get_ports {cipher[41]}]
set_load -pin_load 0 [get_ports {cipher[40]}]
set_load -pin_load 0 [get_ports {cipher[39]}]
set_load -pin_load 0 [get_ports {cipher[38]}]
set_load -pin_load 0 [get_ports {cipher[37]}]
set_load -pin_load 0 [get_ports {cipher[36]}]
set_load -pin_load 0 [get_ports {cipher[35]}]
set_load -pin_load 0 [get_ports {cipher[34]}]
set_load -pin_load 0 [get_ports {cipher[33]}]
set_load -pin_load 0 [get_ports {cipher[32]}]
set_load -pin_load 0 [get_ports {cipher[31]}]
set_load -pin_load 0 [get_ports {cipher[30]}]
set_load -pin_load 0 [get_ports {cipher[29]}]
set_load -pin_load 0 [get_ports {cipher[28]}]
set_load -pin_load 0 [get_ports {cipher[27]}]
set_load -pin_load 0 [get_ports {cipher[26]}]
set_load -pin_load 0 [get_ports {cipher[25]}]
set_load -pin_load 0 [get_ports {cipher[24]}]
set_load -pin_load 0 [get_ports {cipher[23]}]
set_load -pin_load 0 [get_ports {cipher[22]}]
set_load -pin_load 0 [get_ports {cipher[21]}]
set_load -pin_load 0 [get_ports {cipher[20]}]
set_load -pin_load 0 [get_ports {cipher[19]}]
set_load -pin_load 0 [get_ports {cipher[18]}]
set_load -pin_load 0 [get_ports {cipher[17]}]
set_load -pin_load 0 [get_ports {cipher[16]}]
set_load -pin_load 0 [get_ports {cipher[15]}]
set_load -pin_load 0 [get_ports {cipher[14]}]
set_load -pin_load 0 [get_ports {cipher[13]}]
set_load -pin_load 0 [get_ports {cipher[12]}]
set_load -pin_load 0 [get_ports {cipher[11]}]
set_load -pin_load 0 [get_ports {cipher[10]}]
set_load -pin_load 0 [get_ports {cipher[9]}]
set_load -pin_load 0 [get_ports {cipher[8]}]
set_load -pin_load 0 [get_ports {cipher[7]}]
set_load -pin_load 0 [get_ports {cipher[6]}]
set_load -pin_load 0 [get_ports {cipher[5]}]
set_load -pin_load 0 [get_ports {cipher[4]}]
set_load -pin_load 0 [get_ports {cipher[3]}]
set_load -pin_load 0 [get_ports {cipher[2]}]
set_load -pin_load 0 [get_ports {cipher[1]}]
set_load -pin_load 0 [get_ports {cipher[0]}]
set_load -pin_load 0 [get_ports Dvld]
create_clock [get_ports clk]  -period 62.5  -waveform {0 31.25}
set_clock_uncertainty -setup 0  [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports reset]
set_input_delay -clock clk  0  [get_ports {rdata1[31]}]
set_input_delay -clock clk  0  [get_ports {rdata1[30]}]
set_input_delay -clock clk  0  [get_ports {rdata1[29]}]
set_input_delay -clock clk  0  [get_ports {rdata1[28]}]
set_input_delay -clock clk  0  [get_ports {rdata1[27]}]
set_input_delay -clock clk  0  [get_ports {rdata1[26]}]
set_input_delay -clock clk  0  [get_ports {rdata1[25]}]
set_input_delay -clock clk  0  [get_ports {rdata1[24]}]
set_input_delay -clock clk  0  [get_ports {rdata1[23]}]
set_input_delay -clock clk  0  [get_ports {rdata1[22]}]
set_input_delay -clock clk  0  [get_ports {rdata1[21]}]
set_input_delay -clock clk  0  [get_ports {rdata1[20]}]
set_input_delay -clock clk  0  [get_ports {rdata1[19]}]
set_input_delay -clock clk  0  [get_ports {rdata1[18]}]
set_input_delay -clock clk  0  [get_ports {rdata1[17]}]
set_input_delay -clock clk  0  [get_ports {rdata1[16]}]
set_input_delay -clock clk  0  [get_ports {rdata1[15]}]
set_input_delay -clock clk  0  [get_ports {rdata1[14]}]
set_input_delay -clock clk  0  [get_ports {rdata1[13]}]
set_input_delay -clock clk  0  [get_ports {rdata1[12]}]
set_input_delay -clock clk  0  [get_ports {rdata1[11]}]
set_input_delay -clock clk  0  [get_ports {rdata1[10]}]
set_input_delay -clock clk  0  [get_ports {rdata1[9]}]
set_input_delay -clock clk  0  [get_ports {rdata1[8]}]
set_input_delay -clock clk  0  [get_ports {rdata1[7]}]
set_input_delay -clock clk  0  [get_ports {rdata1[6]}]
set_input_delay -clock clk  0  [get_ports {rdata1[5]}]
set_input_delay -clock clk  0  [get_ports {rdata1[4]}]
set_input_delay -clock clk  0  [get_ports {rdata1[3]}]
set_input_delay -clock clk  0  [get_ports {rdata1[2]}]
set_input_delay -clock clk  0  [get_ports {rdata1[1]}]
set_input_delay -clock clk  0  [get_ports {rdata1[0]}]
set_input_delay -clock clk  0  [get_ports {rdata2[31]}]
set_input_delay -clock clk  0  [get_ports {rdata2[30]}]
set_input_delay -clock clk  0  [get_ports {rdata2[29]}]
set_input_delay -clock clk  0  [get_ports {rdata2[28]}]
set_input_delay -clock clk  0  [get_ports {rdata2[27]}]
set_input_delay -clock clk  0  [get_ports {rdata2[26]}]
set_input_delay -clock clk  0  [get_ports {rdata2[25]}]
set_input_delay -clock clk  0  [get_ports {rdata2[24]}]
set_input_delay -clock clk  0  [get_ports {rdata2[23]}]
set_input_delay -clock clk  0  [get_ports {rdata2[22]}]
set_input_delay -clock clk  0  [get_ports {rdata2[21]}]
set_input_delay -clock clk  0  [get_ports {rdata2[20]}]
set_input_delay -clock clk  0  [get_ports {rdata2[19]}]
set_input_delay -clock clk  0  [get_ports {rdata2[18]}]
set_input_delay -clock clk  0  [get_ports {rdata2[17]}]
set_input_delay -clock clk  0  [get_ports {rdata2[16]}]
set_input_delay -clock clk  0  [get_ports {rdata2[15]}]
set_input_delay -clock clk  0  [get_ports {rdata2[14]}]
set_input_delay -clock clk  0  [get_ports {rdata2[13]}]
set_input_delay -clock clk  0  [get_ports {rdata2[12]}]
set_input_delay -clock clk  0  [get_ports {rdata2[11]}]
set_input_delay -clock clk  0  [get_ports {rdata2[10]}]
set_input_delay -clock clk  0  [get_ports {rdata2[9]}]
set_input_delay -clock clk  0  [get_ports {rdata2[8]}]
set_input_delay -clock clk  0  [get_ports {rdata2[7]}]
set_input_delay -clock clk  0  [get_ports {rdata2[6]}]
set_input_delay -clock clk  0  [get_ports {rdata2[5]}]
set_input_delay -clock clk  0  [get_ports {rdata2[4]}]
set_input_delay -clock clk  0  [get_ports {rdata2[3]}]
set_input_delay -clock clk  0  [get_ports {rdata2[2]}]
set_input_delay -clock clk  0  [get_ports {rdata2[1]}]
set_input_delay -clock clk  0  [get_ports {rdata2[0]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[33]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[32]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[31]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[30]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[29]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[28]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[27]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[26]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[25]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[24]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[23]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[22]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[21]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[20]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[19]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[18]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[17]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[16]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[15]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[14]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[13]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[12]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[11]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[10]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[9]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[8]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[7]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[6]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[5]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[4]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[3]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[2]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[1]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata1[0]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[33]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[32]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[31]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[30]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[29]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[28]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[27]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[26]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[25]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[24]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[23]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[22]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[21]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[20]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[19]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[18]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[17]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[16]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[15]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[14]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[13]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[12]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[11]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[10]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[9]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[8]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[7]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[6]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[5]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[4]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[3]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[2]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[1]}]
set_input_delay -clock clk  0  [get_ports {dbp_rdata2[0]}]
set_input_delay -clock clk  0  [get_ports wait_en]
set_output_delay -clock clk  0  [get_ports {add1[31]}]
set_output_delay -clock clk  0  [get_ports {add1[30]}]
set_output_delay -clock clk  0  [get_ports {add1[29]}]
set_output_delay -clock clk  0  [get_ports {add1[28]}]
set_output_delay -clock clk  0  [get_ports {add1[27]}]
set_output_delay -clock clk  0  [get_ports {add1[26]}]
set_output_delay -clock clk  0  [get_ports {add1[25]}]
set_output_delay -clock clk  0  [get_ports {add1[24]}]
set_output_delay -clock clk  0  [get_ports {add1[23]}]
set_output_delay -clock clk  0  [get_ports {add1[22]}]
set_output_delay -clock clk  0  [get_ports {add1[21]}]
set_output_delay -clock clk  0  [get_ports {add1[20]}]
set_output_delay -clock clk  0  [get_ports {add1[19]}]
set_output_delay -clock clk  0  [get_ports {add1[18]}]
set_output_delay -clock clk  0  [get_ports {add1[17]}]
set_output_delay -clock clk  0  [get_ports {add1[16]}]
set_output_delay -clock clk  0  [get_ports {add1[15]}]
set_output_delay -clock clk  0  [get_ports {add1[14]}]
set_output_delay -clock clk  0  [get_ports {add1[13]}]
set_output_delay -clock clk  0  [get_ports {add1[12]}]
set_output_delay -clock clk  0  [get_ports {add1[11]}]
set_output_delay -clock clk  0  [get_ports {add1[10]}]
set_output_delay -clock clk  0  [get_ports {add1[9]}]
set_output_delay -clock clk  0  [get_ports {add1[8]}]
set_output_delay -clock clk  0  [get_ports {add1[7]}]
set_output_delay -clock clk  0  [get_ports {add1[6]}]
set_output_delay -clock clk  0  [get_ports {add1[5]}]
set_output_delay -clock clk  0  [get_ports {add1[4]}]
set_output_delay -clock clk  0  [get_ports {add1[3]}]
set_output_delay -clock clk  0  [get_ports {add1[2]}]
set_output_delay -clock clk  0  [get_ports {add1[1]}]
set_output_delay -clock clk  0  [get_ports {add1[0]}]
set_output_delay -clock clk  0  [get_ports {wen1[3]}]
set_output_delay -clock clk  0  [get_ports {wen1[2]}]
set_output_delay -clock clk  0  [get_ports {wen1[1]}]
set_output_delay -clock clk  0  [get_ports {wen1[0]}]
set_output_delay -clock clk  0  [get_ports {wdata1[31]}]
set_output_delay -clock clk  0  [get_ports {wdata1[30]}]
set_output_delay -clock clk  0  [get_ports {wdata1[29]}]
set_output_delay -clock clk  0  [get_ports {wdata1[28]}]
set_output_delay -clock clk  0  [get_ports {wdata1[27]}]
set_output_delay -clock clk  0  [get_ports {wdata1[26]}]
set_output_delay -clock clk  0  [get_ports {wdata1[25]}]
set_output_delay -clock clk  0  [get_ports {wdata1[24]}]
set_output_delay -clock clk  0  [get_ports {wdata1[23]}]
set_output_delay -clock clk  0  [get_ports {wdata1[22]}]
set_output_delay -clock clk  0  [get_ports {wdata1[21]}]
set_output_delay -clock clk  0  [get_ports {wdata1[20]}]
set_output_delay -clock clk  0  [get_ports {wdata1[19]}]
set_output_delay -clock clk  0  [get_ports {wdata1[18]}]
set_output_delay -clock clk  0  [get_ports {wdata1[17]}]
set_output_delay -clock clk  0  [get_ports {wdata1[16]}]
set_output_delay -clock clk  0  [get_ports {wdata1[15]}]
set_output_delay -clock clk  0  [get_ports {wdata1[14]}]
set_output_delay -clock clk  0  [get_ports {wdata1[13]}]
set_output_delay -clock clk  0  [get_ports {wdata1[12]}]
set_output_delay -clock clk  0  [get_ports {wdata1[11]}]
set_output_delay -clock clk  0  [get_ports {wdata1[10]}]
set_output_delay -clock clk  0  [get_ports {wdata1[9]}]
set_output_delay -clock clk  0  [get_ports {wdata1[8]}]
set_output_delay -clock clk  0  [get_ports {wdata1[7]}]
set_output_delay -clock clk  0  [get_ports {wdata1[6]}]
set_output_delay -clock clk  0  [get_ports {wdata1[5]}]
set_output_delay -clock clk  0  [get_ports {wdata1[4]}]
set_output_delay -clock clk  0  [get_ports {wdata1[3]}]
set_output_delay -clock clk  0  [get_ports {wdata1[2]}]
set_output_delay -clock clk  0  [get_ports {wdata1[1]}]
set_output_delay -clock clk  0  [get_ports {wdata1[0]}]
set_output_delay -clock clk  0  [get_ports {add2[31]}]
set_output_delay -clock clk  0  [get_ports {add2[30]}]
set_output_delay -clock clk  0  [get_ports {add2[29]}]
set_output_delay -clock clk  0  [get_ports {add2[28]}]
set_output_delay -clock clk  0  [get_ports {add2[27]}]
set_output_delay -clock clk  0  [get_ports {add2[26]}]
set_output_delay -clock clk  0  [get_ports {add2[25]}]
set_output_delay -clock clk  0  [get_ports {add2[24]}]
set_output_delay -clock clk  0  [get_ports {add2[23]}]
set_output_delay -clock clk  0  [get_ports {add2[22]}]
set_output_delay -clock clk  0  [get_ports {add2[21]}]
set_output_delay -clock clk  0  [get_ports {add2[20]}]
set_output_delay -clock clk  0  [get_ports {add2[19]}]
set_output_delay -clock clk  0  [get_ports {add2[18]}]
set_output_delay -clock clk  0  [get_ports {add2[17]}]
set_output_delay -clock clk  0  [get_ports {add2[16]}]
set_output_delay -clock clk  0  [get_ports {add2[15]}]
set_output_delay -clock clk  0  [get_ports {add2[14]}]
set_output_delay -clock clk  0  [get_ports {add2[13]}]
set_output_delay -clock clk  0  [get_ports {add2[12]}]
set_output_delay -clock clk  0  [get_ports {add2[11]}]
set_output_delay -clock clk  0  [get_ports {add2[10]}]
set_output_delay -clock clk  0  [get_ports {add2[9]}]
set_output_delay -clock clk  0  [get_ports {add2[8]}]
set_output_delay -clock clk  0  [get_ports {add2[7]}]
set_output_delay -clock clk  0  [get_ports {add2[6]}]
set_output_delay -clock clk  0  [get_ports {add2[5]}]
set_output_delay -clock clk  0  [get_ports {add2[4]}]
set_output_delay -clock clk  0  [get_ports {add2[3]}]
set_output_delay -clock clk  0  [get_ports {add2[2]}]
set_output_delay -clock clk  0  [get_ports {add2[1]}]
set_output_delay -clock clk  0  [get_ports {add2[0]}]
set_output_delay -clock clk  0  [get_ports {wen2[3]}]
set_output_delay -clock clk  0  [get_ports {wen2[2]}]
set_output_delay -clock clk  0  [get_ports {wen2[1]}]
set_output_delay -clock clk  0  [get_ports {wen2[0]}]
set_output_delay -clock clk  0  [get_ports {wdata2[31]}]
set_output_delay -clock clk  0  [get_ports {wdata2[30]}]
set_output_delay -clock clk  0  [get_ports {wdata2[29]}]
set_output_delay -clock clk  0  [get_ports {wdata2[28]}]
set_output_delay -clock clk  0  [get_ports {wdata2[27]}]
set_output_delay -clock clk  0  [get_ports {wdata2[26]}]
set_output_delay -clock clk  0  [get_ports {wdata2[25]}]
set_output_delay -clock clk  0  [get_ports {wdata2[24]}]
set_output_delay -clock clk  0  [get_ports {wdata2[23]}]
set_output_delay -clock clk  0  [get_ports {wdata2[22]}]
set_output_delay -clock clk  0  [get_ports {wdata2[21]}]
set_output_delay -clock clk  0  [get_ports {wdata2[20]}]
set_output_delay -clock clk  0  [get_ports {wdata2[19]}]
set_output_delay -clock clk  0  [get_ports {wdata2[18]}]
set_output_delay -clock clk  0  [get_ports {wdata2[17]}]
set_output_delay -clock clk  0  [get_ports {wdata2[16]}]
set_output_delay -clock clk  0  [get_ports {wdata2[15]}]
set_output_delay -clock clk  0  [get_ports {wdata2[14]}]
set_output_delay -clock clk  0  [get_ports {wdata2[13]}]
set_output_delay -clock clk  0  [get_ports {wdata2[12]}]
set_output_delay -clock clk  0  [get_ports {wdata2[11]}]
set_output_delay -clock clk  0  [get_ports {wdata2[10]}]
set_output_delay -clock clk  0  [get_ports {wdata2[9]}]
set_output_delay -clock clk  0  [get_ports {wdata2[8]}]
set_output_delay -clock clk  0  [get_ports {wdata2[7]}]
set_output_delay -clock clk  0  [get_ports {wdata2[6]}]
set_output_delay -clock clk  0  [get_ports {wdata2[5]}]
set_output_delay -clock clk  0  [get_ports {wdata2[4]}]
set_output_delay -clock clk  0  [get_ports {wdata2[3]}]
set_output_delay -clock clk  0  [get_ports {wdata2[2]}]
set_output_delay -clock clk  0  [get_ports {wdata2[1]}]
set_output_delay -clock clk  0  [get_ports {wdata2[0]}]
set_output_delay -clock clk  0  [get_ports {dbp_add1[9]}]
set_output_delay -clock clk  0  [get_ports {dbp_add1[8]}]
set_output_delay -clock clk  0  [get_ports {dbp_add1[7]}]
set_output_delay -clock clk  0  [get_ports {dbp_add1[6]}]
set_output_delay -clock clk  0  [get_ports {dbp_add1[5]}]
set_output_delay -clock clk  0  [get_ports {dbp_add1[4]}]
set_output_delay -clock clk  0  [get_ports {dbp_add1[3]}]
set_output_delay -clock clk  0  [get_ports {dbp_add1[2]}]
set_output_delay -clock clk  0  [get_ports {dbp_add1[1]}]
set_output_delay -clock clk  0  [get_ports {dbp_add1[0]}]
set_output_delay -clock clk  0  [get_ports {dbp_add2[9]}]
set_output_delay -clock clk  0  [get_ports {dbp_add2[8]}]
set_output_delay -clock clk  0  [get_ports {dbp_add2[7]}]
set_output_delay -clock clk  0  [get_ports {dbp_add2[6]}]
set_output_delay -clock clk  0  [get_ports {dbp_add2[5]}]
set_output_delay -clock clk  0  [get_ports {dbp_add2[4]}]
set_output_delay -clock clk  0  [get_ports {dbp_add2[3]}]
set_output_delay -clock clk  0  [get_ports {dbp_add2[2]}]
set_output_delay -clock clk  0  [get_ports {dbp_add2[1]}]
set_output_delay -clock clk  0  [get_ports {dbp_add2[0]}]
set_output_delay -clock clk  0  [get_ports dbp_wen2]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[33]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[32]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[31]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[30]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[29]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[28]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[27]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[26]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[25]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[24]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[23]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[22]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[21]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[20]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[19]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[18]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[17]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[16]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[15]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[14]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[13]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[12]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[11]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[10]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[9]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[8]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[7]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[6]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[5]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[4]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[3]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[2]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[1]}]
set_output_delay -clock clk  0  [get_ports {dbp_wdata2[0]}]
set_output_delay -clock clk  0  [get_ports {cipher[127]}]
set_output_delay -clock clk  0  [get_ports {cipher[126]}]
set_output_delay -clock clk  0  [get_ports {cipher[125]}]
set_output_delay -clock clk  0  [get_ports {cipher[124]}]
set_output_delay -clock clk  0  [get_ports {cipher[123]}]
set_output_delay -clock clk  0  [get_ports {cipher[122]}]
set_output_delay -clock clk  0  [get_ports {cipher[121]}]
set_output_delay -clock clk  0  [get_ports {cipher[120]}]
set_output_delay -clock clk  0  [get_ports {cipher[119]}]
set_output_delay -clock clk  0  [get_ports {cipher[118]}]
set_output_delay -clock clk  0  [get_ports {cipher[117]}]
set_output_delay -clock clk  0  [get_ports {cipher[116]}]
set_output_delay -clock clk  0  [get_ports {cipher[115]}]
set_output_delay -clock clk  0  [get_ports {cipher[114]}]
set_output_delay -clock clk  0  [get_ports {cipher[113]}]
set_output_delay -clock clk  0  [get_ports {cipher[112]}]
set_output_delay -clock clk  0  [get_ports {cipher[111]}]
set_output_delay -clock clk  0  [get_ports {cipher[110]}]
set_output_delay -clock clk  0  [get_ports {cipher[109]}]
set_output_delay -clock clk  0  [get_ports {cipher[108]}]
set_output_delay -clock clk  0  [get_ports {cipher[107]}]
set_output_delay -clock clk  0  [get_ports {cipher[106]}]
set_output_delay -clock clk  0  [get_ports {cipher[105]}]
set_output_delay -clock clk  0  [get_ports {cipher[104]}]
set_output_delay -clock clk  0  [get_ports {cipher[103]}]
set_output_delay -clock clk  0  [get_ports {cipher[102]}]
set_output_delay -clock clk  0  [get_ports {cipher[101]}]
set_output_delay -clock clk  0  [get_ports {cipher[100]}]
set_output_delay -clock clk  0  [get_ports {cipher[99]}]
set_output_delay -clock clk  0  [get_ports {cipher[98]}]
set_output_delay -clock clk  0  [get_ports {cipher[97]}]
set_output_delay -clock clk  0  [get_ports {cipher[96]}]
set_output_delay -clock clk  0  [get_ports {cipher[95]}]
set_output_delay -clock clk  0  [get_ports {cipher[94]}]
set_output_delay -clock clk  0  [get_ports {cipher[93]}]
set_output_delay -clock clk  0  [get_ports {cipher[92]}]
set_output_delay -clock clk  0  [get_ports {cipher[91]}]
set_output_delay -clock clk  0  [get_ports {cipher[90]}]
set_output_delay -clock clk  0  [get_ports {cipher[89]}]
set_output_delay -clock clk  0  [get_ports {cipher[88]}]
set_output_delay -clock clk  0  [get_ports {cipher[87]}]
set_output_delay -clock clk  0  [get_ports {cipher[86]}]
set_output_delay -clock clk  0  [get_ports {cipher[85]}]
set_output_delay -clock clk  0  [get_ports {cipher[84]}]
set_output_delay -clock clk  0  [get_ports {cipher[83]}]
set_output_delay -clock clk  0  [get_ports {cipher[82]}]
set_output_delay -clock clk  0  [get_ports {cipher[81]}]
set_output_delay -clock clk  0  [get_ports {cipher[80]}]
set_output_delay -clock clk  0  [get_ports {cipher[79]}]
set_output_delay -clock clk  0  [get_ports {cipher[78]}]
set_output_delay -clock clk  0  [get_ports {cipher[77]}]
set_output_delay -clock clk  0  [get_ports {cipher[76]}]
set_output_delay -clock clk  0  [get_ports {cipher[75]}]
set_output_delay -clock clk  0  [get_ports {cipher[74]}]
set_output_delay -clock clk  0  [get_ports {cipher[73]}]
set_output_delay -clock clk  0  [get_ports {cipher[72]}]
set_output_delay -clock clk  0  [get_ports {cipher[71]}]
set_output_delay -clock clk  0  [get_ports {cipher[70]}]
set_output_delay -clock clk  0  [get_ports {cipher[69]}]
set_output_delay -clock clk  0  [get_ports {cipher[68]}]
set_output_delay -clock clk  0  [get_ports {cipher[67]}]
set_output_delay -clock clk  0  [get_ports {cipher[66]}]
set_output_delay -clock clk  0  [get_ports {cipher[65]}]
set_output_delay -clock clk  0  [get_ports {cipher[64]}]
set_output_delay -clock clk  0  [get_ports {cipher[63]}]
set_output_delay -clock clk  0  [get_ports {cipher[62]}]
set_output_delay -clock clk  0  [get_ports {cipher[61]}]
set_output_delay -clock clk  0  [get_ports {cipher[60]}]
set_output_delay -clock clk  0  [get_ports {cipher[59]}]
set_output_delay -clock clk  0  [get_ports {cipher[58]}]
set_output_delay -clock clk  0  [get_ports {cipher[57]}]
set_output_delay -clock clk  0  [get_ports {cipher[56]}]
set_output_delay -clock clk  0  [get_ports {cipher[55]}]
set_output_delay -clock clk  0  [get_ports {cipher[54]}]
set_output_delay -clock clk  0  [get_ports {cipher[53]}]
set_output_delay -clock clk  0  [get_ports {cipher[52]}]
set_output_delay -clock clk  0  [get_ports {cipher[51]}]
set_output_delay -clock clk  0  [get_ports {cipher[50]}]
set_output_delay -clock clk  0  [get_ports {cipher[49]}]
set_output_delay -clock clk  0  [get_ports {cipher[48]}]
set_output_delay -clock clk  0  [get_ports {cipher[47]}]
set_output_delay -clock clk  0  [get_ports {cipher[46]}]
set_output_delay -clock clk  0  [get_ports {cipher[45]}]
set_output_delay -clock clk  0  [get_ports {cipher[44]}]
set_output_delay -clock clk  0  [get_ports {cipher[43]}]
set_output_delay -clock clk  0  [get_ports {cipher[42]}]
set_output_delay -clock clk  0  [get_ports {cipher[41]}]
set_output_delay -clock clk  0  [get_ports {cipher[40]}]
set_output_delay -clock clk  0  [get_ports {cipher[39]}]
set_output_delay -clock clk  0  [get_ports {cipher[38]}]
set_output_delay -clock clk  0  [get_ports {cipher[37]}]
set_output_delay -clock clk  0  [get_ports {cipher[36]}]
set_output_delay -clock clk  0  [get_ports {cipher[35]}]
set_output_delay -clock clk  0  [get_ports {cipher[34]}]
set_output_delay -clock clk  0  [get_ports {cipher[33]}]
set_output_delay -clock clk  0  [get_ports {cipher[32]}]
set_output_delay -clock clk  0  [get_ports {cipher[31]}]
set_output_delay -clock clk  0  [get_ports {cipher[30]}]
set_output_delay -clock clk  0  [get_ports {cipher[29]}]
set_output_delay -clock clk  0  [get_ports {cipher[28]}]
set_output_delay -clock clk  0  [get_ports {cipher[27]}]
set_output_delay -clock clk  0  [get_ports {cipher[26]}]
set_output_delay -clock clk  0  [get_ports {cipher[25]}]
set_output_delay -clock clk  0  [get_ports {cipher[24]}]
set_output_delay -clock clk  0  [get_ports {cipher[23]}]
set_output_delay -clock clk  0  [get_ports {cipher[22]}]
set_output_delay -clock clk  0  [get_ports {cipher[21]}]
set_output_delay -clock clk  0  [get_ports {cipher[20]}]
set_output_delay -clock clk  0  [get_ports {cipher[19]}]
set_output_delay -clock clk  0  [get_ports {cipher[18]}]
set_output_delay -clock clk  0  [get_ports {cipher[17]}]
set_output_delay -clock clk  0  [get_ports {cipher[16]}]
set_output_delay -clock clk  0  [get_ports {cipher[15]}]
set_output_delay -clock clk  0  [get_ports {cipher[14]}]
set_output_delay -clock clk  0  [get_ports {cipher[13]}]
set_output_delay -clock clk  0  [get_ports {cipher[12]}]
set_output_delay -clock clk  0  [get_ports {cipher[11]}]
set_output_delay -clock clk  0  [get_ports {cipher[10]}]
set_output_delay -clock clk  0  [get_ports {cipher[9]}]
set_output_delay -clock clk  0  [get_ports {cipher[8]}]
set_output_delay -clock clk  0  [get_ports {cipher[7]}]
set_output_delay -clock clk  0  [get_ports {cipher[6]}]
set_output_delay -clock clk  0  [get_ports {cipher[5]}]
set_output_delay -clock clk  0  [get_ports {cipher[4]}]
set_output_delay -clock clk  0  [get_ports {cipher[3]}]
set_output_delay -clock clk  0  [get_ports {cipher[2]}]
set_output_delay -clock clk  0  [get_ports {cipher[1]}]
set_output_delay -clock clk  0  [get_ports {cipher[0]}]
set_output_delay -clock clk  0  [get_ports Dvld]
